---
title: "deconv_SPADE"
author: "mgautheret"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---
```{r, parameters }
working_dir<-"/home/genouest/cnrs_umr6290/mgauth/"
out_dir<-"/home/genouest/cnrs_umr6290/mgauth/out/"
sample_name<-"V43T08-051_D"
spatial_matrix<-paste0("real_data/Visium_FFPE_",sample_name,"/filtered_data/Visium_FFPE_",sample_name,"norm_clust.rds")
sc_reference<-"single_cell_data/sc_integ/deconvPDAC_ref_sc_int.rds"
all_markers<-"single_cell_data/sc_integ/CellTypes_Markers_All_cells.rds"
tissue_position<-paste0("real_data/Visium_FFPE_",sample_name,"/outs/spatial/tissue_positions.csv")
nclust=7 #indicate number of cluster identified with spaGCN
```

```{r, library loading }
#!/usr/bin/env Rscript 
library(tidyverse)
library(SPADE)
library(Biobase)
library(Seurat)
library(scatterpie)
library(pheatmap)
```

```{r, data loading}
setwd(working_dir)

spaData<-readRDS(spatial_matrix)
sc<-readRDS(sc_reference)
markers<-readRDS(all_markers)
location <-read.csv(tissue_position)
```

```{r, convert data for SPADE}

#--------Spatial dataset-------------# 
pred_df <- data.frame(barcode =rownames(spaData@meta.data), 
                      pred =as.character(spaData@meta.data$pred))

location<-inner_join(location,pred_df,by="barcode")
location$domain<-as.integer(spaData@meta.data$pred)-1
location$location <- paste(location$pxl_row_in_fullres,
location$pxl_col_in_fullres, sep = "x")

#--------Integrated dataset conversion to expression set--------------# 
expression <-sc$sce
refData<-ExpressionSet(expression)
phenoData(refData)<-AnnotatedDataFrame(sc$pheno) 

```

```{r, create reference matrix}
scref=scRefer(input_data=refData, ct_var="cellType",
sample_var="SubjectName")

```

```{r, estimate coefficients for each cell types for each spatial domain}
marker_list=unlist(markers) 
pseudo.spatial<-GetAssayData(spaData, assay= "RNA", slot= "counts") 
pseudo.spatial<-as.matrix(pseudo.spatial) 
bar_loc=location[,c(1,9)]
col_pseudo=as.data.frame(colnames(pseudo.spatial))
colnames(col_pseudo)='barcode'

col_final<-left_join(col_pseudo,bar_loc, by = 'barcode')
colnames(pseudo.spatial)=col_final$location
nlay=max(location$domain)

CTperLayer=CTperDom(loc=location,stcount=pseudo.spatial,scref=scref,sign_list=marker_list,lasso=F) #lasso=F for ElasticNet regression, lasso=T for Lasso regression 

```

```{r, deconvolution for each spatial domains}
CTest=SPADE(stcount=pseudo.spatial,scref=scref, sign_list=markers,
loc=location, ctData=CTperLayer, offset=0.5)
```

```{r, integration of deconvolution results in each domain and visualisation}

all_rownames <- unlist(lapply(seq_len(nclust), function(i) rownames(CTest[[i]])))
all_colnames <- unique(unlist(lapply(CTest[1:nclust], colnames)))
estCT=matrix(0,ncol = length(all_colnames),length(all_rownames))
rownames(estCT)=all_rownames
colnames(estCT)=all_colnames

for (n in seq_along(CTest)) {
  rn <- rownames(CTest[[n]])
  cn <- colnames(CTest[[n]])
  estCT[rn, cn] <- CTest[[n]]
}

estCT_final=cbind(estCT, location = rownames(estCT)) 
estCT_final<-as.data.frame(estCT_final)
location$location <- as.character(location$location)
estCT_final$location <- as.character(estCT_final$location) 
fuldat <-full_join(location, estCT_final, by = "location")

fuldat$x_pixel=location$pxl_row_in_fullres
fuldat$y_pixel=location$pxl_col_in_fullres 
print(str(fuldat))

write.csv(fuldat,paste0(out_dir,sample_name,"_deconvolution_matrix.csv")) #save deconvolution dataframe


fuldat <- fuldat %>%
  mutate(across(all_of(all_colnames), as.numeric))


colors = c( "Mono.Macro" = "palegreen4", "Dendritic.cells" =
"chartreuse1", "Fibro.Stellate" = "deeppink2", "Endothelial cell" =
"thistle4", "T.cells" = "mediumseagreen", "iCAF" = "orchid2", "myCAF" =
"slategray2","apCAF" = "purple", "B.cells" = "springgreen2", "Basal" = "orange",
"Classic" = "blue1", "Acinar" = "brown2", "Endocrine" = "firebrick",
"Ductal" = "gold" )

fuldat$x_pixel=as.numeric(fuldat$x_pixel)
fuldat$y_pixel=as.numeric(fuldat$y_pixel)

pdf(paste0(out_dir,sample_name,"_deconvolution.pdf")) 
ggplot() + geom_scatterpie(aes(x = x_pixel, y = y_pixel), data = fuldat,
cols = all_colnames, pie_scale = 0.3, color = NA) +
coord_equal() + scale_fill_manual(values = colors) +
theme(panel.background = element_blank(), plot.background =
element_blank(), axis.text = element_blank(), axis.ticks =
element_blank(), axis.title = element_blank(), strip.text =
element_text(face = "bold", size = 12), legend.position = "right",
legend.title = element_blank(), legend.text = element_text(size = 12,
face = "bold")) 
dev.off()
```

```{r, co-localisation matrix}

co_localization_score <- function(df, typeA, typeB, threshold = 0.0) { #Computes co-localization score for 2 cell types
  SA <- as.numeric(df[[typeA]] >= threshold)
  SB <- as.numeric(df[[typeB]] >= threshold)
  numerator <- sum(SA == 1 & SB == 1)
  denominator <- sum(SA == 1 | SB == 1)
  if (denominator == 0) {
    return(0.0)
  }
  return(numerator / denominator)
}

compute_score_matrix <- function(df, threshold = 0.0) { #apply co-localisation score for all cell types using the co_localization_score function
  cell_types <- cell_type
  score_mat <- matrix(0, nrow = length(cell_types), ncol = length(cell_types),
                      dimnames = list(cell_types, cell_types))
  for (i in cell_types) {
    for (j in cell_types) {
      score_mat[i, j] <- co_localization_score(df, i, j, threshold)
    }
  }
  return(score_mat)
}

cell_type= names(markers)[which(names(markers) %in% colnames(fuldat))]

score_matrix<-compute_score_matrix(fuldat, 0.1) # detection threshold recommended by authors for 10X Visium data

pdf(paste0(out_dir,sample_name,"_co_loc_matrix.pdf"))
pheatmap(score_matrix,
         display_numbers = TRUE, 
         cluster_rows = FALSE,
         cluster_cols = FALSE,
         color =colorRampPalette(c("white", "red"))(100),
         main = "Co-localization Score Matrix")

dev.off()
```



